### ISSUE TITLE
Custom thumbnail

### ISSUE THREAD

**Issue by ericmann** [ericmann/WP-Publication-Archive#13]
It would be nice to be able to upload a custom thumbnail for pdf files, so that you can get cover of a magazine displayed.

**Comment by wordfiend84** [comment]
I definitely second this one. I love your plugin but my client has asked for a custom thumbnail for some publications.

**Comment by ericmann** [comment]
@wordfiend84 Development is all but halted while I work on some paying projects.  But if you add the functionality yourself, feel free to submit a pull request.  Or, if you wanted to make a contribution to ongoing development, I might be able to carve out some time of my own.  Think of it as subcontracting development.

**Comment by wordfiend84** [comment]
oh I wish I had the skill. :) 

---

Ashley Sargent
Content & Research
Cityofmoms.com
571.277.2992 
(formerly Surebaby.com)

**Comment by ericmann** [comment]
There is now a feature to allow you to upload a custom thumbnail for Publications (as of 2.5).  This thumbnail is not currently used by any of the template files, but you can use it in your own skinned templates to display cover images.
