### ISSUE TITLE
Shortcode with no publications matching category displays all publications

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [ericmann/WP-Publication-Archive#14]
Archive shortcodes with a category parameter display _all_ publications if there are no publications matching the category array. 

This threw me off a bit; I'd expect instead to see a failure message along the lines of "No categories matched the post". Would a pull request for this be welcome?

**Comment by ericmann** [comment]
That was the intended behavior - basically, it was supposed to not fail if you hadn't actually added anything to that category.  But in hindsight, this was a poor design decision.  So a pull request that instead displays an error message would be very welcome.

**Comment by MatthewEppelsheimer** [comment]
http://i.am.whoa.cc/onit

**Comment by MatthewEppelsheimer** [comment]
Closed by https://github.com/ericmann/WP-Publication-Archive/pull/16
