### ISSUE TITLE
Category shortcode chokes on hyphens in category slugs and white space in category names

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [ericmann/WP-Publication-Archive#15]
If the category name has whitespace, and/or if the category slug has a hyphen, the shortcode category filter fails (behaves like #14). 

I'm satisfied that this is real from my testing on two different sites. I'm less sure this is a bug in the plugin, and not somehow expected behavior, or related to an issue with core. 

I'm even less sure what to do about it. Looking at code now, but this is stretching my level. (Which is good. But.) Could it be related to the use of `trim()` on line 245 of class.wp-plugin-archive.php?

**Comment by ericmann** [comment]
Been a while since this was posted, but it doesn't seem to be an issue any more.  An important note is that my original documentation was wrong. The category filter accepts a list of _names_ not slugs for checking.  And, from what I can tell, passing in category names with spaces works just fine.
