### ISSUE TITLE
pdfs get corrupted on download

### ISSUE THREAD

**Issue by rkshakya** [ericmann/WP-Publication-Archive#28]
Hi,
I am using 2.5.7.2 version of WP-Publication Archive plugin on WP 3.4.2
In that setting, the pdfs get corrupted upon downloading. (The browser does not open the pdf citing similar message)
I have tried out the fix suggested at http://wordpress.org/support/topic/plugin-wp-publication-archive-problem-opening-some-files
but that is not helping either.
Could you please suggest a fix for this problem?
Thank you

**Comment by ericmann** [comment]
That thread is for a much older version of the plugin. `openfile.php` no longer exists, for example.

Can you provide links to your site so I can see what's going on?
