### ISSUE TITLE
Category count mismatch

### ISSUE THREAD

**Issue by alexmansfield** [ericmann/WP-Publication-Archive#36]
It seems that the publication post type shares the "Categories" taxonomy with the posts post type. In the Publication Categories sidebar widget, if the "Show publication counts" checkbox is checked, it appears to count both posts and publications. However, when a category is selected, only publications are displayed on the resulting page, leading to a mismatch in the number of publications shown vs the number suggested in the sidebar.

**Comment by ericmann** [comment]
This is a core issue related to the fact that taxonomies are shared across post types and terms are shared across taxonomies. Unless you're using distinct categories for posts and distinct categories for Publications, this issue will affect _both_.

**Comment by alexmansfield** [comment]
It would be possible to only count the publications in that category, and not posts or pages, correct? That way when a user goes to that category from the widget, the number of posts matches the number in the widget. This may have other ramifications I don't understand, but at least at first glance it seems that the count displayed in the widget could be limited to publications. Feel free to correct me if that's not the case. You're obviously WAY more knowledgeable about this!

**Comment by MatthewEppelsheimer** [comment]
+1. Current behavior broke a client's expectations, and @alexmansfield was able to "fix" it with some plugin hacking, to limit the count by post type. @alexmansfield maybe if you submit a PR with a patch for Eric to review?
