### ISSUE TITLE
Modify template

### ISSUE THREAD

**Issue by LucasHantz** [ericmann/WP-Publication-Archive#4]
Would it be possible in the future to add the ability to edit the primary template outputted by the shortcode `[wp-publication-archive]` ?

You can make it reacheable by a administration option page or by a filter.

**Comment by ericmann** [comment]
I'm actually against adding an option page for this.  However, I am working to make a set of standard template tags so you can build your own output.

Basically, you'll just build a template with a loop similar to WordPress' default post loop ... then you can have the template look and function however you want.
